<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?scdStore version="2"?><scannerInfo id="org.eclipse.cdt.make.core.discoveredScannerInfo">
    <instance id="org.omnetpp.cdt.gnu.config.debug.2050203857">
        <collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)" removed="true"/>
            <includePath path="/Users/tanvipatil/VANETs/omnetpp-6.1/include"/>
            <definedSymbol symbol="__llvm__=1"/>
            <definedSymbol symbol="__clang__=1"/>
            <definedSymbol symbol="__clang_major__=16"/>
            <definedSymbol symbol="__clang_minor__=0"/>
            <definedSymbol symbol="__clang_patchlevel__=0"/>
            <definedSymbol symbol="__clang_version__=&quot;16.0.0 (clang-1600.0.26.6)&quot;"/>
            <definedSymbol symbol="__GNUC__=4"/>
            <definedSymbol symbol="__GNUC_MINOR__=2"/>
            <definedSymbol symbol="__GNUC_PATCHLEVEL__=1"/>
            <definedSymbol symbol="__GXX_ABI_VERSION=1002"/>
            <definedSymbol symbol="__GNUG__=4"/>
            <definedSymbol symbol="__GXX_WEAK__=1"/>
            <definedSymbol symbol="__ATOMIC_RELAXED=0"/>
            <definedSymbol symbol="__ATOMIC_CONSUME=1"/>
            <definedSymbol symbol="__ATOMIC_ACQUIRE=2"/>
            <definedSymbol symbol="__ATOMIC_RELEASE=3"/>
            <definedSymbol symbol="__ATOMIC_ACQ_REL=4"/>
            <definedSymbol symbol="__ATOMIC_SEQ_CST=5"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_WORK_ITEM=0"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_WORK_GROUP=1"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_DEVICE=2"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_SUB_GROUP=4"/>
            <definedSymbol symbol="__FPCLASS_SNAN=0x0001"/>
            <definedSymbol symbol="__FPCLASS_QNAN=0x0002"/>
            <definedSymbol symbol="__FPCLASS_NEGINF=0x0004"/>
            <definedSymbol symbol="__FPCLASS_NEGNORMAL=0x0008"/>
            <definedSymbol symbol="__FPCLASS_NEGSUBNORMAL=0x0010"/>
            <definedSymbol symbol="__FPCLASS_NEGZERO=0x0020"/>
            <definedSymbol symbol="__FPCLASS_POSZERO=0x0040"/>
            <definedSymbol symbol="__FPCLASS_POSSUBNORMAL=0x0080"/>
            <definedSymbol symbol="__FPCLASS_POSNORMAL=0x0100"/>
            <definedSymbol symbol="__FPCLASS_POSINF=0x0200"/>
            <definedSymbol symbol="__PRAGMA_REDEFINE_EXTNAME=1"/>
            <definedSymbol symbol="__VERSION__=&quot;Apple LLVM 16.0.0 (clang-1600.0.26.6)&quot;"/>
            <definedSymbol symbol="__OBJC_BOOL_IS_BOOL=1"/>
            <definedSymbol symbol="__cpp_rtti=199711L"/>
            <definedSymbol symbol="__cpp_exceptions=199711L"/>
            <definedSymbol symbol="__cpp_threadsafe_static_init=200806L"/>
            <definedSymbol symbol="__cpp_named_character_escapes=202207L"/>
            <definedSymbol symbol="__cpp_impl_destroying_delete=201806L"/>
            <definedSymbol symbol="__CONSTANT_CFSTRINGS__=1"/>
            <definedSymbol symbol="__block=__attribute__((__blocks__(byref)))"/>
            <definedSymbol symbol="__BLOCKS__=1"/>
            <definedSymbol symbol="__EXCEPTIONS=1"/>
            <definedSymbol symbol="__GXX_RTTI=1"/>
            <definedSymbol symbol="__DEPRECATED=1"/>
            <definedSymbol symbol="__private_extern__=extern"/>
            <definedSymbol symbol="__clang_literal_encoding__=&quot;UTF-8&quot;"/>
            <definedSymbol symbol="__clang_wide_literal_encoding__=&quot;UTF-32&quot;"/>
            <definedSymbol symbol="__ORDER_LITTLE_ENDIAN__=1234"/>
            <definedSymbol symbol="__ORDER_BIG_ENDIAN__=4321"/>
            <definedSymbol symbol="__ORDER_PDP_ENDIAN__=3412"/>
            <definedSymbol symbol="__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__"/>
            <definedSymbol symbol="__LITTLE_ENDIAN__=1"/>
            <definedSymbol symbol="_LP64=1"/>
            <definedSymbol symbol="__LP64__=1"/>
            <definedSymbol symbol="__CHAR_BIT__=8"/>
            <definedSymbol symbol="__BOOL_WIDTH__=8"/>
            <definedSymbol symbol="__SHRT_WIDTH__=16"/>
            <definedSymbol symbol="__INT_WIDTH__=32"/>
            <definedSymbol symbol="__LONG_WIDTH__=64"/>
            <definedSymbol symbol="__LLONG_WIDTH__=64"/>
            <definedSymbol symbol="__BITINT_MAXWIDTH__=128"/>
            <definedSymbol symbol="__SCHAR_MAX__=127"/>
            <definedSymbol symbol="__SHRT_MAX__=32767"/>
            <definedSymbol symbol="__INT_MAX__=2147483647"/>
            <definedSymbol symbol="__LONG_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__LONG_LONG_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__WCHAR_MAX__=2147483647"/>
            <definedSymbol symbol="__WCHAR_WIDTH__=32"/>
            <definedSymbol symbol="__WINT_MAX__=2147483647"/>
            <definedSymbol symbol="__WINT_WIDTH__=32"/>
            <definedSymbol symbol="__INTMAX_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__INTMAX_WIDTH__=64"/>
            <definedSymbol symbol="__SIZE_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__SIZE_WIDTH__=64"/>
            <definedSymbol symbol="__UINTMAX_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__UINTMAX_WIDTH__=64"/>
            <definedSymbol symbol="__PTRDIFF_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__PTRDIFF_WIDTH__=64"/>
            <definedSymbol symbol="__INTPTR_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__INTPTR_WIDTH__=64"/>
            <definedSymbol symbol="__UINTPTR_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__UINTPTR_WIDTH__=64"/>
            <definedSymbol symbol="__SIZEOF_DOUBLE__=8"/>
            <definedSymbol symbol="__SIZEOF_FLOAT__=4"/>
            <definedSymbol symbol="__SIZEOF_INT__=4"/>
            <definedSymbol symbol="__SIZEOF_LONG__=8"/>
            <definedSymbol symbol="__SIZEOF_LONG_DOUBLE__=8"/>
            <definedSymbol symbol="__SIZEOF_LONG_LONG__=8"/>
            <definedSymbol symbol="__SIZEOF_POINTER__=8"/>
            <definedSymbol symbol="__SIZEOF_SHORT__=2"/>
            <definedSymbol symbol="__SIZEOF_PTRDIFF_T__=8"/>
            <definedSymbol symbol="__SIZEOF_SIZE_T__=8"/>
            <definedSymbol symbol="__SIZEOF_WCHAR_T__=4"/>
            <definedSymbol symbol="__SIZEOF_WINT_T__=4"/>
            <definedSymbol symbol="__SIZEOF_INT128__=16"/>
            <definedSymbol symbol="__INTMAX_TYPE__=long int"/>
            <definedSymbol symbol="__INTMAX_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__INTMAX_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__INTMAX_C_SUFFIX__=L"/>
            <definedSymbol symbol="__UINTMAX_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__UINTMAX_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__UINTMAX_C_SUFFIX__=UL"/>
            <definedSymbol symbol="__PTRDIFF_TYPE__=long int"/>
            <definedSymbol symbol="__PTRDIFF_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__PTRDIFF_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__INTPTR_TYPE__=long int"/>
            <definedSymbol symbol="__INTPTR_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__INTPTR_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__SIZE_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__SIZE_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__SIZE_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__SIZE_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__SIZE_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__WCHAR_TYPE__=int"/>
            <definedSymbol symbol="__WINT_TYPE__=int"/>
            <definedSymbol symbol="__SIG_ATOMIC_MAX__=2147483647"/>
            <definedSymbol symbol="__SIG_ATOMIC_WIDTH__=32"/>
            <definedSymbol symbol="__CHAR16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__CHAR32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINTPTR_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__UINTPTR_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__FLT16_DENORM_MIN__=5.9604644775390625e-8F16"/>
            <definedSymbol symbol="__FLT16_HAS_DENORM__=1"/>
            <definedSymbol symbol="__FLT16_DIG__=3"/>
            <definedSymbol symbol="__FLT16_DECIMAL_DIG__=5"/>
            <definedSymbol symbol="__FLT16_EPSILON__=9.765625e-4F16"/>
            <definedSymbol symbol="__FLT16_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__FLT16_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__FLT16_MANT_DIG__=11"/>
            <definedSymbol symbol="__FLT16_MAX_10_EXP__=4"/>
            <definedSymbol symbol="__FLT16_MAX_EXP__=16"/>
            <definedSymbol symbol="__FLT16_MAX__=6.5504e+4F16"/>
            <definedSymbol symbol="__FLT16_MIN_10_EXP__=(-4)"/>
            <definedSymbol symbol="__FLT16_MIN_EXP__=(-13)"/>
            <definedSymbol symbol="__FLT16_MIN__=6.103515625e-5F16"/>
            <definedSymbol symbol="__FLT_DENORM_MIN__=1.40129846e-45F"/>
            <definedSymbol symbol="__FLT_HAS_DENORM__=1"/>
            <definedSymbol symbol="__FLT_DIG__=6"/>
            <definedSymbol symbol="__FLT_DECIMAL_DIG__=9"/>
            <definedSymbol symbol="__FLT_EPSILON__=1.19209290e-7F"/>
            <definedSymbol symbol="__FLT_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__FLT_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__FLT_MANT_DIG__=24"/>
            <definedSymbol symbol="__FLT_MAX_10_EXP__=38"/>
            <definedSymbol symbol="__FLT_MAX_EXP__=128"/>
            <definedSymbol symbol="__FLT_MAX__=3.40282347e+38F"/>
            <definedSymbol symbol="__FLT_MIN_10_EXP__=(-37)"/>
            <definedSymbol symbol="__FLT_MIN_EXP__=(-125)"/>
            <definedSymbol symbol="__FLT_MIN__=1.17549435e-38F"/>
            <definedSymbol symbol="__DBL_DENORM_MIN__=4.9406564584124654e-324"/>
            <definedSymbol symbol="__DBL_HAS_DENORM__=1"/>
            <definedSymbol symbol="__DBL_DIG__=15"/>
            <definedSymbol symbol="__DBL_DECIMAL_DIG__=17"/>
            <definedSymbol symbol="__DBL_EPSILON__=2.2204460492503131e-16"/>
            <definedSymbol symbol="__DBL_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__DBL_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__DBL_MANT_DIG__=53"/>
            <definedSymbol symbol="__DBL_MAX_10_EXP__=308"/>
            <definedSymbol symbol="__DBL_MAX_EXP__=1024"/>
            <definedSymbol symbol="__DBL_MAX__=1.7976931348623157e+308"/>
            <definedSymbol symbol="__DBL_MIN_10_EXP__=(-307)"/>
            <definedSymbol symbol="__DBL_MIN_EXP__=(-1021)"/>
            <definedSymbol symbol="__DBL_MIN__=2.2250738585072014e-308"/>
            <definedSymbol symbol="__LDBL_DENORM_MIN__=4.9406564584124654e-324L"/>
            <definedSymbol symbol="__LDBL_HAS_DENORM__=1"/>
            <definedSymbol symbol="__LDBL_DIG__=15"/>
            <definedSymbol symbol="__LDBL_DECIMAL_DIG__=17"/>
            <definedSymbol symbol="__LDBL_EPSILON__=2.2204460492503131e-16L"/>
            <definedSymbol symbol="__LDBL_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__LDBL_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__LDBL_MANT_DIG__=53"/>
            <definedSymbol symbol="__LDBL_MAX_10_EXP__=308"/>
            <definedSymbol symbol="__LDBL_MAX_EXP__=1024"/>
            <definedSymbol symbol="__LDBL_MAX__=1.7976931348623157e+308L"/>
            <definedSymbol symbol="__LDBL_MIN_10_EXP__=(-307)"/>
            <definedSymbol symbol="__LDBL_MIN_EXP__=(-1021)"/>
            <definedSymbol symbol="__LDBL_MIN__=2.2250738585072014e-308L"/>
            <definedSymbol symbol="__POINTER_WIDTH__=64"/>
            <definedSymbol symbol="__BIGGEST_ALIGNMENT__=8"/>
            <definedSymbol symbol="__INT8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__INT8_C_SUFFIX__="/>
            <definedSymbol symbol="__INT16_TYPE__=short"/>
            <definedSymbol symbol="__INT16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__INT16_C_SUFFIX__="/>
            <definedSymbol symbol="__INT32_TYPE__=int"/>
            <definedSymbol symbol="__INT32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__INT32_C_SUFFIX__="/>
            <definedSymbol symbol="__INT64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__INT64_C_SUFFIX__=LL"/>
            <definedSymbol symbol="__UINT8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__UINT8_C_SUFFIX__="/>
            <definedSymbol symbol="__UINT8_MAX__=255"/>
            <definedSymbol symbol="__INT8_MAX__=127"/>
            <definedSymbol symbol="__UINT16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__UINT16_C_SUFFIX__="/>
            <definedSymbol symbol="__UINT16_MAX__=65535"/>
            <definedSymbol symbol="__INT16_MAX__=32767"/>
            <definedSymbol symbol="__UINT32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__UINT32_C_SUFFIX__=U"/>
            <definedSymbol symbol="__UINT32_MAX__=4294967295U"/>
            <definedSymbol symbol="__INT32_MAX__=2147483647"/>
            <definedSymbol symbol="__UINT64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__UINT64_C_SUFFIX__=ULL"/>
            <definedSymbol symbol="__UINT64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__INT64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_LEAST8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT_LEAST8_MAX__=127"/>
            <definedSymbol symbol="__INT_LEAST8_WIDTH__=8"/>
            <definedSymbol symbol="__INT_LEAST8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT_LEAST8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT_LEAST8_MAX__=255"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__INT_LEAST16_TYPE__=short"/>
            <definedSymbol symbol="__INT_LEAST16_MAX__=32767"/>
            <definedSymbol symbol="__INT_LEAST16_WIDTH__=16"/>
            <definedSymbol symbol="__INT_LEAST16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT_LEAST16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT_LEAST16_MAX__=65535"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__INT_LEAST32_TYPE__=int"/>
            <definedSymbol symbol="__INT_LEAST32_MAX__=2147483647"/>
            <definedSymbol symbol="__INT_LEAST32_WIDTH__=32"/>
            <definedSymbol symbol="__INT_LEAST32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT_LEAST32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT_LEAST32_MAX__=4294967295U"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__INT_LEAST64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT_LEAST64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_LEAST64_WIDTH__=64"/>
            <definedSymbol symbol="__INT_LEAST64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT_LEAST64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT_LEAST64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__INT_FAST8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT_FAST8_MAX__=127"/>
            <definedSymbol symbol="__INT_FAST8_WIDTH__=8"/>
            <definedSymbol symbol="__INT_FAST8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT_FAST8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT_FAST8_MAX__=255"/>
            <definedSymbol symbol="__UINT_FAST8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__INT_FAST16_TYPE__=short"/>
            <definedSymbol symbol="__INT_FAST16_MAX__=32767"/>
            <definedSymbol symbol="__INT_FAST16_WIDTH__=16"/>
            <definedSymbol symbol="__INT_FAST16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT_FAST16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT_FAST16_MAX__=65535"/>
            <definedSymbol symbol="__UINT_FAST16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__INT_FAST32_TYPE__=int"/>
            <definedSymbol symbol="__INT_FAST32_MAX__=2147483647"/>
            <definedSymbol symbol="__INT_FAST32_WIDTH__=32"/>
            <definedSymbol symbol="__INT_FAST32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT_FAST32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT_FAST32_MAX__=4294967295U"/>
            <definedSymbol symbol="__UINT_FAST32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__INT_FAST64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT_FAST64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_FAST64_WIDTH__=64"/>
            <definedSymbol symbol="__INT_FAST64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT_FAST64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT_FAST64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__UINT_FAST64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__USER_LABEL_PREFIX__=_"/>
            <definedSymbol symbol="__NO_MATH_ERRNO__=1"/>
            <definedSymbol symbol="__FINITE_MATH_ONLY__=0"/>
            <definedSymbol symbol="__GNUC_GNU_INLINE__=1"/>
            <definedSymbol symbol="__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1"/>
            <definedSymbol symbol="__CLANG_ATOMIC_BOOL_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_SHORT_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_INT_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_LONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_LLONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_POINTER_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_BOOL_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR16_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR32_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_WCHAR_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_SHORT_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_INT_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_LONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_LLONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_POINTER_LOCK_FREE=2"/>
            <definedSymbol symbol="__NO_INLINE__=1"/>
            <definedSymbol symbol="__PIC__=2"/>
            <definedSymbol symbol="__pic__=2"/>
            <definedSymbol symbol="__FLT_RADIX__=2"/>
            <definedSymbol symbol="__DECIMAL_DIG__=__LDBL_DECIMAL_DIG__"/>
            <definedSymbol symbol="__SSP__=1"/>
            <definedSymbol symbol="__nonnull=_Nonnull"/>
            <definedSymbol symbol="__null_unspecified=_Null_unspecified"/>
            <definedSymbol symbol="__nullable=_Nullable"/>
            <definedSymbol symbol="__GLIBCXX_TYPE_INT_N_0=__int128"/>
            <definedSymbol symbol="__GLIBCXX_BITSIZE_INT_N_0=128"/>
            <definedSymbol symbol="__AARCH64EL__=1"/>
            <definedSymbol symbol="__aarch64__=1"/>
            <definedSymbol symbol="__GCC_ASM_FLAG_OUTPUTS__=1"/>
            <definedSymbol symbol="__AARCH64_CMODEL_SMALL__=1"/>
            <definedSymbol symbol="__ARM_ACLE=200"/>
            <definedSymbol symbol="__ARM_ARCH=8"/>
            <definedSymbol symbol="__ARM_ARCH_PROFILE='A'"/>
            <definedSymbol symbol="__ARM_64BIT_STATE=1"/>
            <definedSymbol symbol="__ARM_PCS_AAPCS64=1"/>
            <definedSymbol symbol="__ARM_ARCH_ISA_A64=1"/>
            <definedSymbol symbol="__ARM_FEATURE_CLZ=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FMA=1"/>
            <definedSymbol symbol="__ARM_FEATURE_LDREX=0xF"/>
            <definedSymbol symbol="__ARM_FEATURE_IDIV=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DIV=1"/>
            <definedSymbol symbol="__ARM_FEATURE_NUMERIC_MAXMIN=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DIRECTED_ROUNDING=1"/>
            <definedSymbol symbol="__ARM_ALIGN_MAX_STACK_PWR=4"/>
            <definedSymbol symbol="__ARM_FP=0xE"/>
            <definedSymbol symbol="__ARM_FP16_FORMAT_IEEE=1"/>
            <definedSymbol symbol="__ARM_FP16_ARGS=1"/>
            <definedSymbol symbol="__ARM_SIZEOF_WCHAR_T=4"/>
            <definedSymbol symbol="__ARM_SIZEOF_MINIMAL_ENUM=4"/>
            <definedSymbol symbol="__ARM_NEON=1"/>
            <definedSymbol symbol="__ARM_NEON_FP=0xE"/>
            <definedSymbol symbol="__ARM_FEATURE_CRC32=1"/>
            <definedSymbol symbol="__ARM_FEATURE_RCPC=1"/>
            <definedSymbol symbol="__HAVE_FUNCTION_MULTI_VERSIONING=1"/>
            <definedSymbol symbol="__ARM_FEATURE_CRYPTO=1"/>
            <definedSymbol symbol="__ARM_FEATURE_AES=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA2=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA3=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA512=1"/>
            <definedSymbol symbol="__ARM_FEATURE_UNALIGNED=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_VECTOR_ARITHMETIC=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_SCALAR_ARITHMETIC=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DOTPROD=1"/>
            <definedSymbol symbol="__ARM_FEATURE_ATOMICS=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_FML=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FRINT=1"/>
            <definedSymbol symbol="__ARM_FEATURE_BTI=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_3__=1"/>
            <definedSymbol symbol="__ARM_FEATURE_COMPLEX=1"/>
            <definedSymbol symbol="__ARM_FEATURE_JCVT=1"/>
            <definedSymbol symbol="__ARM_FEATURE_PAUTH=1"/>
            <definedSymbol symbol="__ARM_FEATURE_QRDMX=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_4__=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_5__=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1"/>
            <definedSymbol symbol="__FP_FAST_FMA=1"/>
            <definedSymbol symbol="__FP_FAST_FMAF=1"/>
            <definedSymbol symbol="__AARCH64_SIMD__=1"/>
            <definedSymbol symbol="__ARM64_ARCH_8__=1"/>
            <definedSymbol symbol="__ARM_NEON__=1"/>
            <definedSymbol symbol="__REGISTER_PREFIX__="/>
            <definedSymbol symbol="__arm64=1"/>
            <definedSymbol symbol="__arm64__=1"/>
            <definedSymbol symbol="__APPLE_CC__=6000"/>
            <definedSymbol symbol="__APPLE__=1"/>
            <definedSymbol symbol="__STDC_NO_THREADS__=1"/>
            <definedSymbol symbol="__apple_build_version__=16000026"/>
            <definedSymbol symbol="__weak=__attribute__((objc_gc(weak)))"/>
            <definedSymbol symbol="__strong="/>
            <definedSymbol symbol="__unsafe_unretained="/>
            <definedSymbol symbol="__DYNAMIC__=1"/>
            <definedSymbol symbol="__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__=150000"/>
            <definedSymbol symbol="__ENVIRONMENT_OS_VERSION_MIN_REQUIRED__=150000"/>
            <definedSymbol symbol="__MACH__=1"/>
            <definedSymbol symbol="__STDC__=1"/>
            <definedSymbol symbol="__STDC_HOSTED__=1"/>
            <definedSymbol symbol="__cplusplus=199711L"/>
            <definedSymbol symbol="__STDCPP_DEFAULT_NEW_ALIGNMENT__=16UL"/>
            <definedSymbol symbol="__STDCPP_THREADS__=1"/>
            <definedSymbol symbol="__STDC_UTF_16__=1"/>
            <definedSymbol symbol="__STDC_UTF_32__=1"/>
            <definedSymbol symbol="__GCC_HAVE_DWARF2_CFI_ASM=1"/>
        </collector>
    </instance>
    <instance id="org.omnetpp.cdt.gnu.config.release.645101804">
        <collector id="org.eclipse.cdt.make.core.PerProjectSICollector">
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"/>
            <includePath path="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)" removed="true"/>
            <includePath path="/Users/tanvipatil/VANETs/omnetpp-6.1/include"/>
            <definedSymbol symbol="__llvm__=1"/>
            <definedSymbol symbol="__clang__=1"/>
            <definedSymbol symbol="__clang_major__=16"/>
            <definedSymbol symbol="__clang_minor__=0"/>
            <definedSymbol symbol="__clang_patchlevel__=0"/>
            <definedSymbol symbol="__clang_version__=&quot;16.0.0 (clang-1600.0.26.6)&quot;"/>
            <definedSymbol symbol="__GNUC__=4"/>
            <definedSymbol symbol="__GNUC_MINOR__=2"/>
            <definedSymbol symbol="__GNUC_PATCHLEVEL__=1"/>
            <definedSymbol symbol="__GXX_ABI_VERSION=1002"/>
            <definedSymbol symbol="__GNUG__=4"/>
            <definedSymbol symbol="__GXX_WEAK__=1"/>
            <definedSymbol symbol="__ATOMIC_RELAXED=0"/>
            <definedSymbol symbol="__ATOMIC_CONSUME=1"/>
            <definedSymbol symbol="__ATOMIC_ACQUIRE=2"/>
            <definedSymbol symbol="__ATOMIC_RELEASE=3"/>
            <definedSymbol symbol="__ATOMIC_ACQ_REL=4"/>
            <definedSymbol symbol="__ATOMIC_SEQ_CST=5"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_WORK_ITEM=0"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_WORK_GROUP=1"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_DEVICE=2"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3"/>
            <definedSymbol symbol="__OPENCL_MEMORY_SCOPE_SUB_GROUP=4"/>
            <definedSymbol symbol="__FPCLASS_SNAN=0x0001"/>
            <definedSymbol symbol="__FPCLASS_QNAN=0x0002"/>
            <definedSymbol symbol="__FPCLASS_NEGINF=0x0004"/>
            <definedSymbol symbol="__FPCLASS_NEGNORMAL=0x0008"/>
            <definedSymbol symbol="__FPCLASS_NEGSUBNORMAL=0x0010"/>
            <definedSymbol symbol="__FPCLASS_NEGZERO=0x0020"/>
            <definedSymbol symbol="__FPCLASS_POSZERO=0x0040"/>
            <definedSymbol symbol="__FPCLASS_POSSUBNORMAL=0x0080"/>
            <definedSymbol symbol="__FPCLASS_POSNORMAL=0x0100"/>
            <definedSymbol symbol="__FPCLASS_POSINF=0x0200"/>
            <definedSymbol symbol="__PRAGMA_REDEFINE_EXTNAME=1"/>
            <definedSymbol symbol="__VERSION__=&quot;Apple LLVM 16.0.0 (clang-1600.0.26.6)&quot;"/>
            <definedSymbol symbol="__OBJC_BOOL_IS_BOOL=1"/>
            <definedSymbol symbol="__cpp_rtti=199711L"/>
            <definedSymbol symbol="__cpp_exceptions=199711L"/>
            <definedSymbol symbol="__cpp_threadsafe_static_init=200806L"/>
            <definedSymbol symbol="__cpp_named_character_escapes=202207L"/>
            <definedSymbol symbol="__cpp_impl_destroying_delete=201806L"/>
            <definedSymbol symbol="__CONSTANT_CFSTRINGS__=1"/>
            <definedSymbol symbol="__block=__attribute__((__blocks__(byref)))"/>
            <definedSymbol symbol="__BLOCKS__=1"/>
            <definedSymbol symbol="__EXCEPTIONS=1"/>
            <definedSymbol symbol="__GXX_RTTI=1"/>
            <definedSymbol symbol="__DEPRECATED=1"/>
            <definedSymbol symbol="__private_extern__=extern"/>
            <definedSymbol symbol="__clang_literal_encoding__=&quot;UTF-8&quot;"/>
            <definedSymbol symbol="__clang_wide_literal_encoding__=&quot;UTF-32&quot;"/>
            <definedSymbol symbol="__ORDER_LITTLE_ENDIAN__=1234"/>
            <definedSymbol symbol="__ORDER_BIG_ENDIAN__=4321"/>
            <definedSymbol symbol="__ORDER_PDP_ENDIAN__=3412"/>
            <definedSymbol symbol="__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__"/>
            <definedSymbol symbol="__LITTLE_ENDIAN__=1"/>
            <definedSymbol symbol="_LP64=1"/>
            <definedSymbol symbol="__LP64__=1"/>
            <definedSymbol symbol="__CHAR_BIT__=8"/>
            <definedSymbol symbol="__BOOL_WIDTH__=8"/>
            <definedSymbol symbol="__SHRT_WIDTH__=16"/>
            <definedSymbol symbol="__INT_WIDTH__=32"/>
            <definedSymbol symbol="__LONG_WIDTH__=64"/>
            <definedSymbol symbol="__LLONG_WIDTH__=64"/>
            <definedSymbol symbol="__BITINT_MAXWIDTH__=128"/>
            <definedSymbol symbol="__SCHAR_MAX__=127"/>
            <definedSymbol symbol="__SHRT_MAX__=32767"/>
            <definedSymbol symbol="__INT_MAX__=2147483647"/>
            <definedSymbol symbol="__LONG_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__LONG_LONG_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__WCHAR_MAX__=2147483647"/>
            <definedSymbol symbol="__WCHAR_WIDTH__=32"/>
            <definedSymbol symbol="__WINT_MAX__=2147483647"/>
            <definedSymbol symbol="__WINT_WIDTH__=32"/>
            <definedSymbol symbol="__INTMAX_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__INTMAX_WIDTH__=64"/>
            <definedSymbol symbol="__SIZE_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__SIZE_WIDTH__=64"/>
            <definedSymbol symbol="__UINTMAX_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__UINTMAX_WIDTH__=64"/>
            <definedSymbol symbol="__PTRDIFF_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__PTRDIFF_WIDTH__=64"/>
            <definedSymbol symbol="__INTPTR_MAX__=9223372036854775807L"/>
            <definedSymbol symbol="__INTPTR_WIDTH__=64"/>
            <definedSymbol symbol="__UINTPTR_MAX__=18446744073709551615UL"/>
            <definedSymbol symbol="__UINTPTR_WIDTH__=64"/>
            <definedSymbol symbol="__SIZEOF_DOUBLE__=8"/>
            <definedSymbol symbol="__SIZEOF_FLOAT__=4"/>
            <definedSymbol symbol="__SIZEOF_INT__=4"/>
            <definedSymbol symbol="__SIZEOF_LONG__=8"/>
            <definedSymbol symbol="__SIZEOF_LONG_DOUBLE__=8"/>
            <definedSymbol symbol="__SIZEOF_LONG_LONG__=8"/>
            <definedSymbol symbol="__SIZEOF_POINTER__=8"/>
            <definedSymbol symbol="__SIZEOF_SHORT__=2"/>
            <definedSymbol symbol="__SIZEOF_PTRDIFF_T__=8"/>
            <definedSymbol symbol="__SIZEOF_SIZE_T__=8"/>
            <definedSymbol symbol="__SIZEOF_WCHAR_T__=4"/>
            <definedSymbol symbol="__SIZEOF_WINT_T__=4"/>
            <definedSymbol symbol="__SIZEOF_INT128__=16"/>
            <definedSymbol symbol="__INTMAX_TYPE__=long int"/>
            <definedSymbol symbol="__INTMAX_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__INTMAX_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__INTMAX_C_SUFFIX__=L"/>
            <definedSymbol symbol="__UINTMAX_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__UINTMAX_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__UINTMAX_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__UINTMAX_C_SUFFIX__=UL"/>
            <definedSymbol symbol="__PTRDIFF_TYPE__=long int"/>
            <definedSymbol symbol="__PTRDIFF_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__PTRDIFF_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__INTPTR_TYPE__=long int"/>
            <definedSymbol symbol="__INTPTR_FMTd__=&quot;ld&quot;"/>
            <definedSymbol symbol="__INTPTR_FMTi__=&quot;li&quot;"/>
            <definedSymbol symbol="__SIZE_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__SIZE_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__SIZE_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__SIZE_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__SIZE_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__WCHAR_TYPE__=int"/>
            <definedSymbol symbol="__WINT_TYPE__=int"/>
            <definedSymbol symbol="__SIG_ATOMIC_MAX__=2147483647"/>
            <definedSymbol symbol="__SIG_ATOMIC_WIDTH__=32"/>
            <definedSymbol symbol="__CHAR16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__CHAR32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINTPTR_TYPE__=long unsigned int"/>
            <definedSymbol symbol="__UINTPTR_FMTo__=&quot;lo&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTu__=&quot;lu&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTx__=&quot;lx&quot;"/>
            <definedSymbol symbol="__UINTPTR_FMTX__=&quot;lX&quot;"/>
            <definedSymbol symbol="__FLT16_DENORM_MIN__=5.9604644775390625e-8F16"/>
            <definedSymbol symbol="__FLT16_HAS_DENORM__=1"/>
            <definedSymbol symbol="__FLT16_DIG__=3"/>
            <definedSymbol symbol="__FLT16_DECIMAL_DIG__=5"/>
            <definedSymbol symbol="__FLT16_EPSILON__=9.765625e-4F16"/>
            <definedSymbol symbol="__FLT16_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__FLT16_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__FLT16_MANT_DIG__=11"/>
            <definedSymbol symbol="__FLT16_MAX_10_EXP__=4"/>
            <definedSymbol symbol="__FLT16_MAX_EXP__=16"/>
            <definedSymbol symbol="__FLT16_MAX__=6.5504e+4F16"/>
            <definedSymbol symbol="__FLT16_MIN_10_EXP__=(-4)"/>
            <definedSymbol symbol="__FLT16_MIN_EXP__=(-13)"/>
            <definedSymbol symbol="__FLT16_MIN__=6.103515625e-5F16"/>
            <definedSymbol symbol="__FLT_DENORM_MIN__=1.40129846e-45F"/>
            <definedSymbol symbol="__FLT_HAS_DENORM__=1"/>
            <definedSymbol symbol="__FLT_DIG__=6"/>
            <definedSymbol symbol="__FLT_DECIMAL_DIG__=9"/>
            <definedSymbol symbol="__FLT_EPSILON__=1.19209290e-7F"/>
            <definedSymbol symbol="__FLT_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__FLT_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__FLT_MANT_DIG__=24"/>
            <definedSymbol symbol="__FLT_MAX_10_EXP__=38"/>
            <definedSymbol symbol="__FLT_MAX_EXP__=128"/>
            <definedSymbol symbol="__FLT_MAX__=3.40282347e+38F"/>
            <definedSymbol symbol="__FLT_MIN_10_EXP__=(-37)"/>
            <definedSymbol symbol="__FLT_MIN_EXP__=(-125)"/>
            <definedSymbol symbol="__FLT_MIN__=1.17549435e-38F"/>
            <definedSymbol symbol="__DBL_DENORM_MIN__=4.9406564584124654e-324"/>
            <definedSymbol symbol="__DBL_HAS_DENORM__=1"/>
            <definedSymbol symbol="__DBL_DIG__=15"/>
            <definedSymbol symbol="__DBL_DECIMAL_DIG__=17"/>
            <definedSymbol symbol="__DBL_EPSILON__=2.2204460492503131e-16"/>
            <definedSymbol symbol="__DBL_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__DBL_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__DBL_MANT_DIG__=53"/>
            <definedSymbol symbol="__DBL_MAX_10_EXP__=308"/>
            <definedSymbol symbol="__DBL_MAX_EXP__=1024"/>
            <definedSymbol symbol="__DBL_MAX__=1.7976931348623157e+308"/>
            <definedSymbol symbol="__DBL_MIN_10_EXP__=(-307)"/>
            <definedSymbol symbol="__DBL_MIN_EXP__=(-1021)"/>
            <definedSymbol symbol="__DBL_MIN__=2.2250738585072014e-308"/>
            <definedSymbol symbol="__LDBL_DENORM_MIN__=4.9406564584124654e-324L"/>
            <definedSymbol symbol="__LDBL_HAS_DENORM__=1"/>
            <definedSymbol symbol="__LDBL_DIG__=15"/>
            <definedSymbol symbol="__LDBL_DECIMAL_DIG__=17"/>
            <definedSymbol symbol="__LDBL_EPSILON__=2.2204460492503131e-16L"/>
            <definedSymbol symbol="__LDBL_HAS_INFINITY__=1"/>
            <definedSymbol symbol="__LDBL_HAS_QUIET_NAN__=1"/>
            <definedSymbol symbol="__LDBL_MANT_DIG__=53"/>
            <definedSymbol symbol="__LDBL_MAX_10_EXP__=308"/>
            <definedSymbol symbol="__LDBL_MAX_EXP__=1024"/>
            <definedSymbol symbol="__LDBL_MAX__=1.7976931348623157e+308L"/>
            <definedSymbol symbol="__LDBL_MIN_10_EXP__=(-307)"/>
            <definedSymbol symbol="__LDBL_MIN_EXP__=(-1021)"/>
            <definedSymbol symbol="__LDBL_MIN__=2.2250738585072014e-308L"/>
            <definedSymbol symbol="__POINTER_WIDTH__=64"/>
            <definedSymbol symbol="__BIGGEST_ALIGNMENT__=8"/>
            <definedSymbol symbol="__INT8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__INT8_C_SUFFIX__="/>
            <definedSymbol symbol="__INT16_TYPE__=short"/>
            <definedSymbol symbol="__INT16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__INT16_C_SUFFIX__="/>
            <definedSymbol symbol="__INT32_TYPE__=int"/>
            <definedSymbol symbol="__INT32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__INT32_C_SUFFIX__="/>
            <definedSymbol symbol="__INT64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__INT64_C_SUFFIX__=LL"/>
            <definedSymbol symbol="__UINT8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__UINT8_C_SUFFIX__="/>
            <definedSymbol symbol="__UINT8_MAX__=255"/>
            <definedSymbol symbol="__INT8_MAX__=127"/>
            <definedSymbol symbol="__UINT16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__UINT16_C_SUFFIX__="/>
            <definedSymbol symbol="__UINT16_MAX__=65535"/>
            <definedSymbol symbol="__INT16_MAX__=32767"/>
            <definedSymbol symbol="__UINT32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__UINT32_C_SUFFIX__=U"/>
            <definedSymbol symbol="__UINT32_MAX__=4294967295U"/>
            <definedSymbol symbol="__INT32_MAX__=2147483647"/>
            <definedSymbol symbol="__UINT64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__UINT64_C_SUFFIX__=ULL"/>
            <definedSymbol symbol="__UINT64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__INT64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_LEAST8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT_LEAST8_MAX__=127"/>
            <definedSymbol symbol="__INT_LEAST8_WIDTH__=8"/>
            <definedSymbol symbol="__INT_LEAST8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT_LEAST8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT_LEAST8_MAX__=255"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__INT_LEAST16_TYPE__=short"/>
            <definedSymbol symbol="__INT_LEAST16_MAX__=32767"/>
            <definedSymbol symbol="__INT_LEAST16_WIDTH__=16"/>
            <definedSymbol symbol="__INT_LEAST16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT_LEAST16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT_LEAST16_MAX__=65535"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__INT_LEAST32_TYPE__=int"/>
            <definedSymbol symbol="__INT_LEAST32_MAX__=2147483647"/>
            <definedSymbol symbol="__INT_LEAST32_WIDTH__=32"/>
            <definedSymbol symbol="__INT_LEAST32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT_LEAST32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT_LEAST32_MAX__=4294967295U"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT_LEAST32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__INT_LEAST64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT_LEAST64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_LEAST64_WIDTH__=64"/>
            <definedSymbol symbol="__INT_LEAST64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT_LEAST64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT_LEAST64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT_LEAST64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__INT_FAST8_TYPE__=signed char"/>
            <definedSymbol symbol="__INT_FAST8_MAX__=127"/>
            <definedSymbol symbol="__INT_FAST8_WIDTH__=8"/>
            <definedSymbol symbol="__INT_FAST8_FMTd__=&quot;hhd&quot;"/>
            <definedSymbol symbol="__INT_FAST8_FMTi__=&quot;hhi&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_TYPE__=unsigned char"/>
            <definedSymbol symbol="__UINT_FAST8_MAX__=255"/>
            <definedSymbol symbol="__UINT_FAST8_FMTo__=&quot;hho&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTu__=&quot;hhu&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTx__=&quot;hhx&quot;"/>
            <definedSymbol symbol="__UINT_FAST8_FMTX__=&quot;hhX&quot;"/>
            <definedSymbol symbol="__INT_FAST16_TYPE__=short"/>
            <definedSymbol symbol="__INT_FAST16_MAX__=32767"/>
            <definedSymbol symbol="__INT_FAST16_WIDTH__=16"/>
            <definedSymbol symbol="__INT_FAST16_FMTd__=&quot;hd&quot;"/>
            <definedSymbol symbol="__INT_FAST16_FMTi__=&quot;hi&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_TYPE__=unsigned short"/>
            <definedSymbol symbol="__UINT_FAST16_MAX__=65535"/>
            <definedSymbol symbol="__UINT_FAST16_FMTo__=&quot;ho&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTu__=&quot;hu&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTx__=&quot;hx&quot;"/>
            <definedSymbol symbol="__UINT_FAST16_FMTX__=&quot;hX&quot;"/>
            <definedSymbol symbol="__INT_FAST32_TYPE__=int"/>
            <definedSymbol symbol="__INT_FAST32_MAX__=2147483647"/>
            <definedSymbol symbol="__INT_FAST32_WIDTH__=32"/>
            <definedSymbol symbol="__INT_FAST32_FMTd__=&quot;d&quot;"/>
            <definedSymbol symbol="__INT_FAST32_FMTi__=&quot;i&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_TYPE__=unsigned int"/>
            <definedSymbol symbol="__UINT_FAST32_MAX__=4294967295U"/>
            <definedSymbol symbol="__UINT_FAST32_FMTo__=&quot;o&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTu__=&quot;u&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTx__=&quot;x&quot;"/>
            <definedSymbol symbol="__UINT_FAST32_FMTX__=&quot;X&quot;"/>
            <definedSymbol symbol="__INT_FAST64_TYPE__=long long int"/>
            <definedSymbol symbol="__INT_FAST64_MAX__=9223372036854775807LL"/>
            <definedSymbol symbol="__INT_FAST64_WIDTH__=64"/>
            <definedSymbol symbol="__INT_FAST64_FMTd__=&quot;lld&quot;"/>
            <definedSymbol symbol="__INT_FAST64_FMTi__=&quot;lli&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_TYPE__=long long unsigned int"/>
            <definedSymbol symbol="__UINT_FAST64_MAX__=18446744073709551615ULL"/>
            <definedSymbol symbol="__UINT_FAST64_FMTo__=&quot;llo&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTu__=&quot;llu&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTx__=&quot;llx&quot;"/>
            <definedSymbol symbol="__UINT_FAST64_FMTX__=&quot;llX&quot;"/>
            <definedSymbol symbol="__USER_LABEL_PREFIX__=_"/>
            <definedSymbol symbol="__NO_MATH_ERRNO__=1"/>
            <definedSymbol symbol="__FINITE_MATH_ONLY__=0"/>
            <definedSymbol symbol="__GNUC_GNU_INLINE__=1"/>
            <definedSymbol symbol="__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1"/>
            <definedSymbol symbol="__CLANG_ATOMIC_BOOL_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_SHORT_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_INT_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_LONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_LLONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__CLANG_ATOMIC_POINTER_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_BOOL_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR16_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_CHAR32_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_WCHAR_T_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_SHORT_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_INT_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_LONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_LLONG_LOCK_FREE=2"/>
            <definedSymbol symbol="__GCC_ATOMIC_POINTER_LOCK_FREE=2"/>
            <definedSymbol symbol="__NO_INLINE__=1"/>
            <definedSymbol symbol="__PIC__=2"/>
            <definedSymbol symbol="__pic__=2"/>
            <definedSymbol symbol="__FLT_RADIX__=2"/>
            <definedSymbol symbol="__DECIMAL_DIG__=__LDBL_DECIMAL_DIG__"/>
            <definedSymbol symbol="__SSP__=1"/>
            <definedSymbol symbol="__nonnull=_Nonnull"/>
            <definedSymbol symbol="__null_unspecified=_Null_unspecified"/>
            <definedSymbol symbol="__nullable=_Nullable"/>
            <definedSymbol symbol="__GLIBCXX_TYPE_INT_N_0=__int128"/>
            <definedSymbol symbol="__GLIBCXX_BITSIZE_INT_N_0=128"/>
            <definedSymbol symbol="__AARCH64EL__=1"/>
            <definedSymbol symbol="__aarch64__=1"/>
            <definedSymbol symbol="__GCC_ASM_FLAG_OUTPUTS__=1"/>
            <definedSymbol symbol="__AARCH64_CMODEL_SMALL__=1"/>
            <definedSymbol symbol="__ARM_ACLE=200"/>
            <definedSymbol symbol="__ARM_ARCH=8"/>
            <definedSymbol symbol="__ARM_ARCH_PROFILE='A'"/>
            <definedSymbol symbol="__ARM_64BIT_STATE=1"/>
            <definedSymbol symbol="__ARM_PCS_AAPCS64=1"/>
            <definedSymbol symbol="__ARM_ARCH_ISA_A64=1"/>
            <definedSymbol symbol="__ARM_FEATURE_CLZ=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FMA=1"/>
            <definedSymbol symbol="__ARM_FEATURE_LDREX=0xF"/>
            <definedSymbol symbol="__ARM_FEATURE_IDIV=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DIV=1"/>
            <definedSymbol symbol="__ARM_FEATURE_NUMERIC_MAXMIN=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DIRECTED_ROUNDING=1"/>
            <definedSymbol symbol="__ARM_ALIGN_MAX_STACK_PWR=4"/>
            <definedSymbol symbol="__ARM_FP=0xE"/>
            <definedSymbol symbol="__ARM_FP16_FORMAT_IEEE=1"/>
            <definedSymbol symbol="__ARM_FP16_ARGS=1"/>
            <definedSymbol symbol="__ARM_SIZEOF_WCHAR_T=4"/>
            <definedSymbol symbol="__ARM_SIZEOF_MINIMAL_ENUM=4"/>
            <definedSymbol symbol="__ARM_NEON=1"/>
            <definedSymbol symbol="__ARM_NEON_FP=0xE"/>
            <definedSymbol symbol="__ARM_FEATURE_CRC32=1"/>
            <definedSymbol symbol="__ARM_FEATURE_RCPC=1"/>
            <definedSymbol symbol="__HAVE_FUNCTION_MULTI_VERSIONING=1"/>
            <definedSymbol symbol="__ARM_FEATURE_CRYPTO=1"/>
            <definedSymbol symbol="__ARM_FEATURE_AES=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA2=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA3=1"/>
            <definedSymbol symbol="__ARM_FEATURE_SHA512=1"/>
            <definedSymbol symbol="__ARM_FEATURE_UNALIGNED=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_VECTOR_ARITHMETIC=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_SCALAR_ARITHMETIC=1"/>
            <definedSymbol symbol="__ARM_FEATURE_DOTPROD=1"/>
            <definedSymbol symbol="__ARM_FEATURE_ATOMICS=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FP16_FML=1"/>
            <definedSymbol symbol="__ARM_FEATURE_FRINT=1"/>
            <definedSymbol symbol="__ARM_FEATURE_BTI=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_3__=1"/>
            <definedSymbol symbol="__ARM_FEATURE_COMPLEX=1"/>
            <definedSymbol symbol="__ARM_FEATURE_JCVT=1"/>
            <definedSymbol symbol="__ARM_FEATURE_PAUTH=1"/>
            <definedSymbol symbol="__ARM_FEATURE_QRDMX=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_4__=1"/>
            <definedSymbol symbol="__ARM_ARCH_8_5__=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1"/>
            <definedSymbol symbol="__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1"/>
            <definedSymbol symbol="__FP_FAST_FMA=1"/>
            <definedSymbol symbol="__FP_FAST_FMAF=1"/>
            <definedSymbol symbol="__AARCH64_SIMD__=1"/>
            <definedSymbol symbol="__ARM64_ARCH_8__=1"/>
            <definedSymbol symbol="__ARM_NEON__=1"/>
            <definedSymbol symbol="__REGISTER_PREFIX__="/>
            <definedSymbol symbol="__arm64=1"/>
            <definedSymbol symbol="__arm64__=1"/>
            <definedSymbol symbol="__APPLE_CC__=6000"/>
            <definedSymbol symbol="__APPLE__=1"/>
            <definedSymbol symbol="__STDC_NO_THREADS__=1"/>
            <definedSymbol symbol="__apple_build_version__=16000026"/>
            <definedSymbol symbol="__weak=__attribute__((objc_gc(weak)))"/>
            <definedSymbol symbol="__strong="/>
            <definedSymbol symbol="__unsafe_unretained="/>
            <definedSymbol symbol="__DYNAMIC__=1"/>
            <definedSymbol symbol="__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__=150000"/>
            <definedSymbol symbol="__ENVIRONMENT_OS_VERSION_MIN_REQUIRED__=150000"/>
            <definedSymbol symbol="__MACH__=1"/>
            <definedSymbol symbol="__STDC__=1"/>
            <definedSymbol symbol="__STDC_HOSTED__=1"/>
            <definedSymbol symbol="__cplusplus=199711L"/>
            <definedSymbol symbol="__STDCPP_DEFAULT_NEW_ALIGNMENT__=16UL"/>
            <definedSymbol symbol="__STDCPP_THREADS__=1"/>
            <definedSymbol symbol="__STDC_UTF_16__=1"/>
            <definedSymbol symbol="__STDC_UTF_32__=1"/>
            <definedSymbol symbol="__GCC_HAVE_DWARF2_CFI_ASM=1"/>
        </collector>
    </instance>
</scannerInfo>
